# Data Analysis - Little project on a Money in Politic
by Reimer Romero

This analysis as part a Python Journalist MOOC.

In [1]:
import pandas as pd

In [2]:
props = pd.read_csv("http://www.firstpythonnotebook.org/_static/committees.csv")

In [3]:
pp=props.prop_name.value_counts().reset_index()
pp

                                                index  prop_name
0   PROPOSITION 057 - CRIMINAL SENTENCES. JUVENILE...         13
1   PROPOSITION 056 - CIGARETTE TAX TO FUND HEALTH...         12
2   PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...         11
3   PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...          9
4   PROPOSITION 055 - TAX EXTENSION TO FUND EDUCAT...          8
5   PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON...          7
6   PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...          7
7   PROPOSITION 059- SB 254 (CHAPTER 20, STATUTES ...          6
8   PROPOSITION 053 - REVENUE BONDS. STATEWIDE VOT...          4
9   PROPOSITION 054 - LEGISLATURE. LEGISLATION AND...          4
10  PROPOSITION 058 - SB 1174 (CHAPTER 753, STATUT...          4
11  PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...          4
12  PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...          4
13  PROPOSITION 052 - STATE FEES ON HOSPITALS. FED...          3
14  PROPOSITION 061- STATE PRESCRIPTION DRUG PURCH...          3
15  PROPOSITION 060- ADULT FILMS. CONDOMS. HEALTH ...          2
16  PROPOSITION 065- CARRY-OUT BAGS. CHARGES. INIT...          1

## Here are the propositions

In [4]:
name66 = pp.iloc[3,0]
name66

'PROPOSITION 066- DEATH PENALTY. PROCEDURES. INITIATIVE STATUTE.'

In [5]:
name63 = pp.iloc[11,0]
name63

'PROPOSITION 063- FIREARMS. AMMUNITION SALES. INTIATIVE STATUTE.'

In [6]:
prop63 = props[props.prop_name == name63]

In [7]:
prop66 = props[props.prop_name == name66]

In [8]:
contribs = pd.read_csv("http://www.firstpythonnotebook.org/_static/contributions.csv")

In [9]:
contribs.head().reset_index()

,index,Unnamed: 0,calaccess_committee_id,committee_name,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
0,0,0,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-09-18,BERGMAN,GRETCHEN,SPRING VALLEY,CA,91978,A NEW PATH,EXECUTIVE DIRECTOR,False,84.0
1,1,1,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-09-18,KAHLE,MYRNA,SAN DIEGO,CA,92109,NATIONAL SCHOOL DISTRICT,TEACHER,False,35.0
2,2,2,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-07-15,MCDEVITT,LEO,ESCONDIDO,CA,92025,LIFE IONIZERS,SEO/CONTENT MANAGER,False,198.0
3,3,3,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-08-10,WARREN-SAMARIPA,STEPHANIE,SAN DIEGO,CA,92116,STEPHANIE WARREN SAMARIPA,ENTREPRENEUR,False,-50.0
4,4,4,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-07-26,WARREN-SAMARIPA,STEPHANIE,SAN DIEGO,CA,92116,STEPHANIE WARREN SAMARIPA,ENTREPRENEUR,True,50.0

In [27]:
oppose63 = merged63[merged63.committee_position == 'OPPOSE']
oppose66 = merged66[merged66.committee_position == 'OPPOSE']

## List of contributors grouping by state -  Firearm and ammuniton sales

In [14]:
merged66.groupby("contributor_state").amount.sum().reset_index().sort_values("amount", ascending=False)

   contributor_state        amount
4                 CA  2.675843e+07
8                 DE  6.140365e+06
7                 DC  1.000565e+06
30                NY  1.539151e+05
17                MA  9.652600e+04
42                WA  4.222500e+04
13                IL  2.037500e+04
39                UT  2.011000e+04
38                TX  1.267500e+04
2                 AZ  1.056000e+04
29                NV  5.180000e+03
27                NJ  3.985000e+03
18                MD  3.390000e+03
40                VA  2.704000e+03
9                 FL  2.580000e+03
34                PA  1.845000e+03
24                NC  1.633000e+03
37                TN  1.500000e+03
10                GA  1.220000e+03
28                NM  1.050000e+03
12                IA  1.005000e+03
41                VT  9.550000e+02
33                OR  8.824000e+02
11                HI  8.250000e+02
1                 AL  7.000000e+02
5                 CO  6.250000e+02
31                OH  5.750000e+02
22                MO  5.250000e+02
19                ME  4.050000e+02
14                KS  4.000000e+02
0                 AK  3.500000e+02
16                LA  3.500000e+02
25                NE  3.250000e+02
20                MI  2.800000e+02
43                WI  2.700000e+02
35                RI  2.450000e+02
15                KY  2.100000e+02
3                 BC  2.100000e+02
36                SC  1.800000e+02
32                OK  1.750000e+02
21                MN  1.500000e+02
26                NH  1.450000e+02
6                 CT  1.290000e+02
23                NB  4.000000e+01

## List of contributors grouping by state -  Death penalty procedures

In [13]:
merged63.groupby(["contributor_state"]).amount.sum().reset_index().sort_values("amount", ascending=False)

   contributor_state      amount
2                 CA  3124081.68
24                NY   107115.00
1                 AZ   101425.00
34                VA    95390.00
4                 CT    40625.00
23                NV     4405.00
32                TX     3675.00
17                MN     2140.00
35                WA     1350.00
14                MA     1200.00
36                WI     1000.00
26                OR      850.00
22                NJ      760.00
9                 IL      725.00
29                SC      650.00
37                WY      500.00
16                MI      450.00
19                NC      400.00
3                 CO      400.00
7                 HI      400.00
6                 GA      385.00
27                PA      350.00
31                TN      300.00
10                IN      300.00
8                 IA      250.00
5                 FL      240.00
13                LA      225.00
25                OH      200.00
33                UT      200.00
28                RI      200.00
15                MD      125.00
11                KS      100.00
12                KY      100.00
30                TE      100.00
21                NH      100.00
18                MO       50.00
20                NE       50.00
0                  A       20.00

## Total contributor amount to each proposition

In [31]:
support63.amount.sum()

2829869.0999999996

In [32]:
support66.amount.sum()

16836069.810002133

## Amount porcentual difference between both propositions

In [45]:
support66.amount.sum()/support63.amount.sum() - 1

4.949416462408857

### It mean, prop 66 is 495% largest that pro 63 in money contribution